
// import { BarLoader } from "react-spinners";
// import { Suspense } from "react";

// export default function Layout({ children }) {
//   return (
//     <div className="px-5">
//       <div className="flex items-center justify-between mb-5">
//         <h1 className="text-6xl font-bold gradient gradient-title">Industry Insights</h1>
//       </div>
//       <Suspense
//         fallback={<BarLoader className="mt-4" width={"100%"} color="gray" />}
//       >
//         {children}
//       </Suspense>
//     </div>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // return (
  //   <html lang="en">
  //     <body
  //       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //     >
  //       {children}
  //     </body>
  //   </html>
  // );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex items-center justify-center min-h-screen bg-gray-100">
          <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
